//João Roberto Savini Merante RA 1886525
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Joao
 */
public class JanelaListaEscorpiao extends javax.swing.JFrame {

    /**
     * Creates new form JanelaListaEscorpiao
     */
    public JanelaListaEscorpiao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listEscorpiao = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista Escorpião");

        listEscorpiao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listEscorpiaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listEscorpiao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void listEscorpiaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listEscorpiaoMouseClicked
        String componente = listEscorpiao.getSelectedValue();
        JOptionPane.showMessageDialog(null, "Escorpiao: " +componente, "Escorpiao selecionado", 1);
    }//GEN-LAST:event_listEscorpiaoMouseClicked

    public void showListEscorpiao(BancoEscorpiao bancoEscorpiao) {
        this.setVisible(true);
        Escorpiao escorpiao = new Escorpiao();
        DefaultListModel modeloListaEscorpiao = new DefaultListModel();
        modeloListaEscorpiao.removeAllElements();

        for (int i = 0; i < bancoEscorpiao.getBdEscorpiao().size(); i++) {
            try {
                escorpiao.setId(bancoEscorpiao.getBdEscorpiao().get(i).getId());
                escorpiao.setQuantidadeOlhos(bancoEscorpiao.getBdEscorpiao().get(i).getQuantidadeOlhos());
                escorpiao.setPeconhento(bancoEscorpiao.getBdEscorpiao().get(i).getPeconhento());
                escorpiao.setEspecie(bancoEscorpiao.getBdEscorpiao().get(i).getEspecie());
                escorpiao.setCor(bancoEscorpiao.getBdEscorpiao().get(i).getCor());
                escorpiao.getRegiao().setPais(bancoEscorpiao.getBdEscorpiao().get(i).getRegiao().getPais());
                escorpiao.getRegiao().setEstado(bancoEscorpiao.getBdEscorpiao().get(i).getRegiao().getEstado());
                escorpiao.setPernas(bancoEscorpiao.getBdEscorpiao().get(i).getPernas());
                escorpiao.setFerrao(bancoEscorpiao.getBdEscorpiao().get(i).getFerrao());
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(null, "Tipo de não aceito", "Erro no cadastro", JOptionPane.ERROR_MESSAGE);
            } catch (OlhosException oe) {
                oe.avisoOlhos();
            }
            modeloListaEscorpiao.addElement(escorpiao.getId() + " - " + escorpiao.getEspecie() + " - "
                    + escorpiao.getQuantidadeOlhos() + " - " + escorpiao.getCor() + " - "
                    + escorpiao.getRegiao().getPais() + " - " + escorpiao.getRegiao().getEstado() + " - "
                    + escorpiao.getPeconhento() + " - " + escorpiao.getFerrao() + " - " + escorpiao.getPernas());
        }
        listEscorpiao.setModel(modeloListaEscorpiao);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaListaEscorpiao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaListaEscorpiao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaListaEscorpiao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaListaEscorpiao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaListaEscorpiao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listEscorpiao;
    // End of variables declaration//GEN-END:variables
}
