//João Roberto Savini Merante RA 1886525
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Joao
 */
public class JanelaComboAranha extends javax.swing.JFrame {

    /**
     * Creates new form JanelaComboAranha
     */
    public JanelaComboAranha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboAranha = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Combo Box Aranha");

        comboAranha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAranhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboAranha, 0, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboAranha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void comboAranhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAranhaActionPerformed
        if(comboAranha.getSelectedIndex()  >= 1){
            String componente = "";
            componente = comboAranha.getSelectedItem().toString();
            JOptionPane.showMessageDialog(null, "Aranha: " +componente, "Escorpiao selecionada", 1);
        }
    }//GEN-LAST:event_comboAranhaActionPerformed

    public void showComboAranha(BancoAranha bancoAranha) {
        this.setVisible(true);
        Aranha aranha = new Aranha();
        
        comboAranha.removeAllItems();
        comboAranha.addItem("Escolha uma opção");

        for (int i = 0; i < bancoAranha.getBdAranha().size(); i++) {
            try {
                aranha.setId(bancoAranha.getBdAranha().get(i).getId());
                aranha.setQuantidadeOlhos(bancoAranha.getBdAranha().get(i).getQuantidadeOlhos());
                aranha.setPeconhento(bancoAranha.getBdAranha().get(i).getPeconhento());
                aranha.setEspecie(bancoAranha.getBdAranha().get(i).getEspecie());
                aranha.setCor(bancoAranha.getBdAranha().get(i).getCor());
                aranha.getRegiao().setPais(bancoAranha.getBdAranha().get(i).getRegiao().getPais());
                aranha.getRegiao().setEstado(bancoAranha.getBdAranha().get(i).getRegiao().getEstado());
                aranha.setTeia(bancoAranha.getBdAranha().get(i).getTeia());
                aranha.setSubOrdem(bancoAranha.getBdAranha().get(i).getSubOrdem());
                aranha.setVeneno(bancoAranha.getBdAranha().get(i).getVeneno());
                aranha.setPernas(bancoAranha.getBdAranha().get(i).getPernas());
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(null, "Tipo de dados não aceito", "Erro no cadastro", JOptionPane.ERROR_MESSAGE);
            } catch (OlhosException oe) {
                oe.avisoOlhos();
            } catch (SubOrdemException soe) {
                soe.avisoSubOrdem();
            }

            comboAranha.addItem(aranha.getId() + " - " + aranha.getEspecie() + " - "
                    + aranha.getSubOrdem() + " - " + aranha.getQuantidadeOlhos() + " - " + aranha.getCor() + " - "
                    + aranha.getRegiao().getPais() + " - " + aranha.getRegiao().getEstado()
                    + " - " + aranha.getTeia() + " - " + aranha.getPeconhento() + " - " + aranha.getVeneno()
                    + " - " + aranha.getPernas());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaComboAranha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaComboAranha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaComboAranha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaComboAranha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaComboAranha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboAranha;
    // End of variables declaration//GEN-END:variables
}
