//João Roberto Savini Merante RA 1886525

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Joao
 */
public class JanelaTabelaEscorpiao extends javax.swing.JFrame {

    /**
     * Creates new form JanelaTabelaEscorpiao
     */
    public JanelaTabelaEscorpiao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableEscorpiao = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tableEscorpiao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Especie", "Qtd Olhos", "Cor", "País", "Estado", "Peçonhento", "Ferrao", "Pernas"
            }
        ));
        tableEscorpiao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEscorpiaoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEscorpiao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1660, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableEscorpiaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEscorpiaoMouseClicked
        String componente1 = "";
        int i;
        //int coluna;
        int linha = tableEscorpiao.getSelectedRow();

        for (i = 0; i < tableEscorpiao.getColumnCount(); i++) {
            componente1 += tableEscorpiao.getModel().getValueAt(tableEscorpiao.getSelectedRow(), i).toString();
            if (i < tableEscorpiao.getColumnCount()) {
                componente1 += " - ";
            }
        }
        JOptionPane.showMessageDialog(null, "Escorpiao: " + componente1, "Escorpiao selecionada", 1);
    }//GEN-LAST:event_tableEscorpiaoMouseClicked

    public void showTableEscorpiao(BancoEscorpiao bancoEscorpiao) {
        this.setVisible(true);
        Escorpiao escorpiao = new Escorpiao();
        DefaultTableModel modeloTabelaEscorpiao = new DefaultTableModel();
        modeloTabelaEscorpiao = (DefaultTableModel) tableEscorpiao.getModel();
        modeloTabelaEscorpiao.setRowCount(0);

        for (int i = 0; i < bancoEscorpiao.getBdEscorpiao().size(); i++) {
            try {
                escorpiao.setId(bancoEscorpiao.getBdEscorpiao().get(i).getId());
                escorpiao.setQuantidadeOlhos(bancoEscorpiao.getBdEscorpiao().get(i).getQuantidadeOlhos());
                escorpiao.setPeconhento(bancoEscorpiao.getBdEscorpiao().get(i).getPeconhento());
                escorpiao.setEspecie(bancoEscorpiao.getBdEscorpiao().get(i).getEspecie());
                escorpiao.setCor(bancoEscorpiao.getBdEscorpiao().get(i).getCor());
                escorpiao.getRegiao().setPais(bancoEscorpiao.getBdEscorpiao().get(i).getRegiao().getPais());
                escorpiao.getRegiao().setEstado(bancoEscorpiao.getBdEscorpiao().get(i).getRegiao().getEstado());
                escorpiao.setPernas(bancoEscorpiao.getBdEscorpiao().get(i).getPernas());
                escorpiao.setFerrao(bancoEscorpiao.getBdEscorpiao().get(i).getFerrao());
            } catch (NumberFormatException nfe) {
                JOptionPane.showMessageDialog(null, "Tipo de não aceito", "Erro no cadastro", JOptionPane.ERROR_MESSAGE);
            } catch (OlhosException oe) {
                oe.avisoOlhos();
            }

            modeloTabelaEscorpiao.insertRow(i, new Object[]{escorpiao.getId(), escorpiao.getEspecie(),
                escorpiao.getQuantidadeOlhos(), escorpiao.getCor(),
                escorpiao.getRegiao().getPais(), escorpiao.getRegiao().getEstado(),
                escorpiao.getPeconhento(), escorpiao.getFerrao(), escorpiao.getPernas()});
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaTabelaEscorpiao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaTabelaEscorpiao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaTabelaEscorpiao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaTabelaEscorpiao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaTabelaEscorpiao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableEscorpiao;
    // End of variables declaration//GEN-END:variables
}
